### ISSUE TITLE
Is torch mode available?

### ISSUE THREAD

**Issue by joaopiopedreira** [nartc/react-native-barcode-mask#1]
Hi, just bumped into your package. Great work BTW! I wonder if we can enable the torch from the RNCamera parent?

**Comment by nartc** [comment]
Hi @joaopiopedreira , thanks! As I understand, this `BarcodeMask` is only a SubView to RNCamera. And to be honest, I've never used torch mode before. Can you elaborate more? Is it something that BarcodeMask should handle?

**Comment by joaopiopedreira** [comment]
Hi @nartc, I have this request from my users. They sometimes need to scan a barcode in a dark or poorly illuminated area. I know that RNCamera has a torch mode (or flash mode: `RNCamera.Constants.FlashMode`) and I'm just wondering if that can be used with no issues.

**Comment by nartc** [comment]
Shouldn't be an issue at all.
