### ISSUE TITLE
showAnimatedLine is freezing sometimes

### ISSUE THREAD

**Issue by Sub-Zero-1** [nartc/react-native-barcode-mask#212]
Hi,
showAnimatedLine is freezing sometimes when showing CameraScreen in first stack navigator with react navigation v.5

We were using BarCodeMask in our CameraScreen successfully with react navigation v.4. I am now working on switching to react navigation v.5. Our code for our CameraScreen hasn't changed. The CameraScreen was placed on a stack navigatior within a tabNavigator. Everything worked like before. The problem is, that we have a tab bar at the bottom which we want to get rid of for the CameraScreen. According to official react navigation documentation we need to replace the CameraScreen outside the TabNavigator, so we placed it in the first stack navigator of our app which then calls first the tabNavigator and then the CameraScreen. In this constilation, the CameraScreen still works like expected, but sometimes (40%) the showAnimatedLine just freezes and I do not know why.I already tried to get "showAnimatedLine" from a state, where the state is first false, and after a timeout of say 2 seconds it sets it to true and the showAnimatedLine gets visible, but also there it freezes 40% of the times, but the camera still works normally. Here the code eample within the first stack navigator where it freezes sometimes.

-> Stack Navigator with tabNavigator and CameraScreen = showAnimatedLine freezes 40% of times.

```
		<AppNavigator.Navigator
			screenOptions={() => ({
				// default config for all screens
				headerHideShadow: true,
				headerShown: true,
				headerTitleAlign: 'center',
				animationEnabled: false,
				headerStyle: { backgroundColor: 'red' },
				initialRouteName: 'TabNavigator',
			})}
		>
			<AppNavigator.Screen
				name="TabNavigatorNavi"
				component={TabNavigatorNavi}
				options={({ navigation, route }) => getHeaderOptions(route, navigation)}
			/>
			<AppNavigator.Screen
				name="CameraScreen"
				component={CameraScreen}
				options={({ navigation }) => getCameraScreenHeaderOptions(navigation)}
			/>
		</AppNavigator.Navigator >
```

Here it works all the time:

-> StackNavigator ->TabNavigator -> StackNavigator with CameraScreen. = works all the time.

How can that happen?

**Comment by nartc** [comment]
@Sub-Zero-1 Thanks for reporting. Would you mind sharing a sample reproduce repository? I can take a look. Also keep in mind that this library was written before Reanimated 2 so issues with animation **could/might** be fixed by implementing Reanimated 2 instead of 1.

**Comment by Sub-Zero-1** [comment]
Sorry, my fault. I have mistaken the library. I have used https://github.com/shahnawaz/react-native-barcode-mask instead of yours. I was not aware, that there are two similar. I switched to your library and it works without freezing! Great! Easy solution. Thanks!
