### ISSUE TITLE
useBarcodeRead Hook is not working properly

### ISSUE THREAD

**Issue by jackyleehong** [nartc/react-native-barcode-mask#3]
There is no any response from the qrcode camera after applying onBarcodeRead from the hook.

**Comment by nartc** [comment]
@jackyleehong Android? Can you provide a repro repo?

**Comment by jackyleehong** [comment]
const {
    barcodeRead,
    onBarcodeRead,
    onBarcodeFinderLayoutChange,
  } = useBarcodeRead(
    isFocused,
    barcodeData => {
      console.log(barcodeData)
      return barcodeData
    },
    processedBarcodeData => { }
  );

<RNCamera
          onBarCodeRead={onBarcodeRead}
          captureAudio={false}
          style={{
            flex: 1,
            justifyContent: 'flex-end',
            alignItems: 'center',
            
          }}
 ...
>
   <BarcodeMask 
            onLayoutChange={onBarcodeFinderLayoutChange}
            edgeColor={'#62B1F6'} showAnimatedLine={false} maskOpacity={0.5}/>
</RNCamera>

I put somethings like this, and somehow there is nothings displayed at console.log there.

**Comment by jackyleehong** [comment]
what I figure out is that for my phone, the x axis and y axis is starting at here as shown in the link below:
https://drive.google.com/file/d/1-uitjUNW7YTgJhaz-G9KR5gWc52PtIzK/view?usp=sharing.

Hopefully it do help.

**Comment by nartc** [comment]
Oh wow that is amazing. I had no idea that the axises are different based on devices. I’ll look into this on the weekend. Definitely a bug. Thanks!

**Comment by jackyleehong** [comment]
From what I have observe, the axis might be the same, but  it may be caused by the stated finderX or finderY position vary from device to device currently.

**Comment by jackyleehong** [comment]
this is what I have done personally to fix the issue for my case for android:

  var _insideBox = function _insideBox(point) {
      var x = 0
      var y = 0
      if (point) {
        x = point.x,
          y = point.y;
      }
      return (x && (x >= finderY - finderX && x <= finderX + finderWidth))
        && (y && (y >= finderY / 2 && y <= finderY / 2 + finderHeight));
    };
