### ISSUE TITLE
barcodeRead is always false even after scanning

### ISSUE THREAD

**Issue by taeingyu** [nartc/react-native-barcode-mask#43]
**To Reproduce**
```javascript
import React, { useRef, useCallback } from 'react';
import { View, StyleSheet } from 'react-native';
import { RNCamera } from 'react-native-camera';
import { BarcodeMask, useBarcodeRead } from '@nartc/react-native-barcode-mask';

function CameraScreen({ navigation }) {
  const camera = useRef(null);

  const handleBarcodeData = useCallback(
    barcodeData => {
      console.log('barcodeData', barcodeData);
      // navigation.goBack();
    },
    [navigation],
  );

  const {
    barcodeRead,
    onBarcodeRead,
    onBarcodeFinderLayoutChange,
  } = useBarcodeRead(
    navigation.isFocused(),
    barcodeData => barcodeData,
    handleBarcodeData,
  );

  console.log('barcodeRead', barcodeRead);

  return (
    <View style={styles.container}>
      <RNCamera
        ref={camera}
        style={{
          flex: 1,
          width: '100%',
        }}
        captureAudio={false}
        onBarCodeRead={onBarcodeRead}
        barcodeTypes={barcodeRead ? [] : [RNCamera.Constants.BarCodeType.qr]}
      >
        <BarcodeMask
          onLayoutChange={onBarcodeFinderLayoutChange}
          maskOpacity={0.5}
          animatedLineColor="#f00"
        />
      </RNCamera>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default CameraScreen;
```

**Expected behavior**
console.log() message should be
```
                                                  (before scanning)
barcodeRead false
                                                  (after scanning)
barcodeData 1234
barcodeRead true
                                                  (stop)
```
However `barcodeRead` is always false, so it does not change `barcodeTypes` prop.
```
                                                  (before scanning)
barcodeRead false
                                                  (after scanning)
barcodeData 1234
barcodeRead false
barcodeData 1234
barcodeRead false
barcodeData 1234
barcodeRead false
...                                               (repeat)
```

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13
 - react-native 0.61, react-native-camera 3.16
 - 1.1.6

**Comment by taeingyu** [comment]
Found one more issue, it also scans not only qrcode but all barcode types despite `barcodeTypes` prop.

**Comment by nartc** [comment]
@taeingyu It would be helpful if you could share a minimal reproducible repo. If not, it would just take a little longer for me to reproduce it. Thanks for reporting the issue. Just a headsup, I'm going to participate in a local Game Jam this weekend so I might not be able to look into this for couple of days.

**Comment by taeingyu** [comment]
@nartc Thanks for quick reply, this is the reproducible repo https://github.com/taeingyu/react-native-barcode-mask-example

**Comment by nartc** [comment]
@taeingyu Thanks. I'll take a look as soon as I have a chance.

**Comment by nartc** [comment]
@taeingyu Please check out the latest release to see if it works out for you. Please read the README regarding `barcodeRead` changed.

**Comment by taeingyu** [comment]
> @taeingyu Please check out the latest release to see if it works out for you. Please read the README regarding `barcodeRead` changed.

It works great! and the new `barcodeReadDelay` is just the feature I was looking for. Thanks!
