### ISSUE TITLE
Make height and width animated

### ISSUE THREAD

**Issue by pawelkondraciuk** [nartc/react-native-barcode-mask#74]
So scan area could have nice transition if height and width will change during the scan, for example to scan something else.

**Comment by nartc** [comment]
Hi @pawelkondraciuk, thanks for opening the issue. Would you mind provide some desired behavior with this change? I'm sorry but I have a hard time visualizing your feature request.

**Comment by pawelkondraciuk** [comment]
Sure, I've modified old version of barcode mask and added `animatedHeight: Animated.Value` property and updated its value in `componentDidUpdate` hook. This way whenever I change height, the mask dimension is changing smoothly.

```
  componentDidUpdate(prevProps: BarcodeMaskProps) {
    if (this.props.height !== prevProps.height) {
      Animated.timing(this.state.animatedHeight, {
        toValue: +this.props.height,
        duration: 150,
      }).start();
    }
  }
```

I works for me but I am pretty sure that it can be done better :)

**Comment by nartc** [comment]
Interesting. Thanks for clarification. I'll think about how I want to do it.

**Comment by nartc** [comment]
@pawelkondraciuk I've been having a hard time trying to animate the width and height. Not sure if you mind sharing some code that you've modifed?

**Comment by nartc** [comment]
Will be revisited when `react-native-reanimated` v2 goes stable.
