### ISSUE TITLE
Can we replace the animation to our own designed animation?

### ISSUE THREAD

**Issue by jackyleehong** [nartc/react-native-barcode-mask#80]

**Comment by nartc** [comment]
Hi,

Interesting request. I believe one way is to have the consumers (you guys) to provide the animated line as a component. I’ll think about how I want to provide that API

Thanks

**Comment by nartc** [comment]
`BarcodeMask` and `BarcodeMaskWithOuter` now have an additional prop called `animatedComponent`. It is a Render Prop and will be called with the computed `width`, `height`
and must return a `ReactElement`.

```typescript
<BarcodeMask animatedComponent={(width, height) => <Text>Custom Animation Component</Text>} />
```
